# Generated by Django 2.2.5 on 2020-01-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20200124_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_day',
            name='date',
            field=models.DateTimeField(verbose_name='Дата рабочего дня'),
        ),
    ]
