# Generated by Django 2.2.5 on 2020-01-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_auto_20200124_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_day',
            name='date',
            field=models.DateField(verbose_name='Дата рабочего дня'),
        ),
    ]
