# Generated by Django 2.2.5 on 2020-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_auto_20200128_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=10, verbose_name='Url'),
        ),
    ]
