# Generated by Django 2.2.5 on 2020-01-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_auto_20200128_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_day',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата рабочего дня'),
        ),
        migrations.AlterField(
            model_name='working_day',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=10, verbose_name='Url'),
        ),
    ]
